services:
  - type: web
    name: commercial-studio
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn pricing_app.wsgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"
