# Generated by Django 6.1.1 on 2026-10-02 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_lead_product_lead_quantity_lead_won_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company / Account Name'),
        ),
        migrations.AddField(
            model_name='lead',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star - Cold Lead'), (2, '2 Stars - Warm Lead'), (3, '3 Stars - Qualified Opportunity'), (4, '4 Stars - Hot Opportunity'), (5, '5 Stars - Key Account / High Priority')], default=3, verbose_name='Customer Rating'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('Suspect', '1. Suspect (S)'), ('Prospect', '2. Prospect (P)'), ('Approach', '3. Approach (A)'), ('Negotiation', '4. Negotiation (N)'), ('Closing', '5. Closing (C)'), ('Order', '6. Order / Won (O)'), ('PostSale', '7. Post-Sale / Payment (P)'), ('Lost', 'Lost')], default='Suspect', max_length=20),
        ),
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('Call', 'Phone Call'), ('Meeting', 'Client Meeting'), ('Email', 'Email Correspondence'), ('Negotiation', 'Price / Terms Negotiation'), ('Note', 'Talk / Discussion Note')], default='Call', max_length=20)),
                ('notes', models.TextField(verbose_name='Talks / Discussion Notes')),
                ('rating_given', models.IntegerField(blank=True, choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_interactions', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
