# Generated by Django 6.1.1 on 2026-10-03 12:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_lead_company_name_lead_rating_alter_lead_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadinteraction',
            name='interaction_type',
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(default='Riyadh', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='lead',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments / Notes'),
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(default='Saudi Arabia', max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='lead',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Added'),
        ),
        migrations.AddField(
            model_name='lead',
            name='est_volume_liters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Est. Volume (L/month)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contact_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Contact Date'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lead ID Code'),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_action',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Next Action'),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_action_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next Action Date'),
        ),
        migrations.AddField(
            model_name='lead',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold')], default='Hot', max_length=20, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='lead',
            name='products_of_interest',
            field=models.TextField(blank=True, null=True, verbose_name='Products of Interest'),
        ),
        migrations.AddField(
            model_name='lead',
            name='segment',
            field=models.CharField(choices=[('Distributor', 'Distributor'), ('Wholesaler', 'Wholesaler'), ('Retailer / Shop', 'Retailer / Shop'), ('Workshop / Service', 'Workshop / Service'), ('Fleet / Transport', 'Fleet / Transport'), ('Industrial', 'Industrial'), ('Marketplace', 'Marketplace'), ('Other', 'Other')], default='Distributor', max_length=100, verbose_name='Segment'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, default='Exhibition', max_length=100, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='lead',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='activity_type',
            field=models.CharField(choices=[('Call', 'Phone Call'), ('WhatsApp', 'WhatsApp Message'), ('Email', 'Email Correspondence'), ('Meeting', 'Client Meeting'), ('Visit', 'On-site Visit'), ('Offer Sent', 'Offer Sent'), ('Samples Sent', 'Samples Sent'), ('Order Received', 'Order Received'), ('Payment Follow-up', 'Payment Follow-up'), ('Note', 'General Note')], default='Call', max_length=30),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='next_step',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Next Step'),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='next_step_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next Step Date'),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='outcome',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('No answer', 'No answer')], default='Positive', max_length=30, verbose_name='Outcome'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company_name',
            field=models.CharField(blank=True, default='Unspecified Company', max_length=255, verbose_name='Company / Account Name'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_name',
            field=models.CharField(max_length=255, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='opportunity_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Opportunity Name'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='rating',
            field=models.IntegerField(default=3, verbose_name='Rating (1-5)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Est. Deal Value (USD)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Interested', 'Interested'), ('Samples Sent', 'Samples Sent'), ('Offer Sent', 'Offer Sent'), ('Negotiation', 'Negotiation'), ('Won', 'Won'), ('Lost', 'Lost'), ('On Hold', 'On Hold'), ('Suspect', 'Suspect (New)'), ('Prospect', 'Prospect (Contacted)'), ('Approach', 'Approach (Interested)'), ('Closing', 'Closing (Negotiation)'), ('Order', 'Order (Won)'), ('PostSale', 'Post-Sale')], default='New', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='leadinteraction',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.lead'),
        ),
        migrations.AlterField(
            model_name='leadinteraction',
            name='notes',
            field=models.TextField(verbose_name='Summary / Discussion Notes'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(max_length=20, unique=True, verbose_name='Client ID Code')),
                ('country', models.CharField(default='United Arab Emirates', max_length=100, verbose_name='Country')),
                ('city', models.CharField(default='Sharjah', max_length=100, verbose_name='City')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('segment', models.CharField(default='Retailer / Shop', max_length=100, verbose_name='Segment')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Contact Person')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Position')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp')),
                ('client_since', models.DateField(blank=True, null=True, verbose_name='Client Since')),
                ('contract_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contract No.')),
                ('payment_terms', models.CharField(choices=[('Prepayment', 'Prepayment'), ('Cash on delivery', 'Cash on delivery'), ('Net 15', 'Net 15'), ('Net 30', 'Net 30'), ('Net 45', 'Net 45'), ('Net 60', 'Net 60'), ('Letter of credit', 'Letter of credit')], default='Net 30', max_length=50, verbose_name='Payment Terms')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Credit Limit (USD)')),
                ('last_order_date', models.DateField(blank=True, null=True, verbose_name='Last Order Date')),
                ('last_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Last Order Value (USD)')),
                ('sales_ytd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sales YTD (USD)')),
                ('avg_volume_liters', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Avg Volume (L/month)')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('At Risk', 'At Risk'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=30, verbose_name='Client Status')),
                ('next_followup_date', models.DateField(blank=True, null=True, verbose_name='Next Follow-up Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Account Manager')),
            ],
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.client'),
        ),
    ]
